#page title
page_title                                : theBartender.ai - Your AI Mixologist!

# App Info
ios_app_id                                : 6738669034                                # Required. Enter iOS app ID to automatically populate name, price and icons (e.g. 718043190).
ios_app_country                           : us                                        # Required outside USA. Enter 2 letter country code as in https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2

appstore_link                             : https://apps.apple.com/us/app/thebartender-ai/id6738669034
playstore_link                            :                                           # Enter Google Play Store URL.
presskit_download_link                    :                                           # Enter a link to downloadable file or (e.g. public Dropbox link to a .zip file). 
                                                                                      # Or upload your press kit file to assets and set path accordingly (e.g. "assets/your_press_kit.zip").

app_icon                                  : assets/TheBartenderAi_AppIcon.png
app_name                                  : theBartender.ai
app_price                                 : 
app_description                           : Your Personal AI Mixologist

enable_smart_app_banner                   : true                                      # Set to true to show a smart app banner at top of page on mobile devices.



# Information About Yourself
your_name                                 : Toan Nguyen                               
your_link                                 : https://thebartender.ai                     
your_city                                 : Atlanta                                
email_address                             : contact_us@thebartender.ai
facebook_username                         :
instagram_username                        :
twitter_username                          : thebartender_ai
github_username                           :
youtube_username                          :
mastodon_link                             :



# Feature List                            Edit, add or remove features to be presented.
features                                  :

  - title                                 : Cocktail Event Planner AI
    description                           : Plan and manage cocktail events effortlessly with AI-powered menu suggestions, shopping lists, and event tools.
    fontawesome_icon_name                 : cocktail
  
  - title                                 : AI-Powered Menu Generator
    description                           : Generate personalized cocktail menus based on event details, guest preferences, and available ingredients.
    fontawesome_icon_name                 : magic
  
  - title                                 : Advanced Shopping List
    description                           : Create a detailed shopping list with quantities, brands, and checklist functionality for seamless preparation.
    fontawesome_icon_name                 : magic
  
  - title                                 : Inventory Management
    description                           : Track and manage your available ingredients and tools to maximize event efficiency.
    fontawesome_icon_name                 : boxes
  
  - title                                 : Recipe Explorer
    description                           : Browse, filter, and favorite cocktail recipes by difficulty, flavor profiles, and more.
    fontawesome_icon_name                 : book
  
  - title                                 : Event Analytics
    description                           : Gain insights into event costs, cocktail preferences, and preparation efficiency.
    fontawesome_icon_name                 : chart-line
  
  - title                                 : Customization Options
    description                           : Tailor event planning with themes, budget levels, and preferred cocktail styles.
    fontawesome_icon_name                 : sliders-h


# Theme Settings
topbar_color                              : "#3CB2B5"
topbar_transparency                       : 0.2
topbar_title_color                        : "#ffffff"

cover_image                               : assets/headerimage.png                    # Replace with alternative image path or image URL.

device_color                              : black                                     # Set to: blue, black, yellow, coral or white.

body_background_color                     : "#FFFFFF"

link_color                                : "#3CB2B5"

app_title_color                           : "#FFFFFF"
app_price_color                           : "#FFFFFF"
app_description_color                     : "#FFFFFF"

feature_title_color                       : "#000000"
feature_text_color                        : "#666666"

feature_icons_foreground_color            : "#3CB2B5"
feature_icons_background_color            : "#e6f7f8"

social_icons_foreground_color             : "#3CB2B5"
social_icons_background_color             : "#e6f7f8"

footer_text_color                         : "#666666"













####################################################
### Jekyll Configuration. No need to touch this. ###
####################################################

# Set the Sass partials directory, as we're using @imports
sass:
  style: :compressed # You might prefer to minify using :compressed

# Exclude these files from your production _site
exclude:
  - LICENSE
  - README.md
  - CNAME

collections:
  pages:
    output: true
    permalink: /:path/

# Markdown rendering
markdown: kramdown
